AWSTemplateFormatVersion: '2010-09-09'
Description: 101Monkeys - Pacer Protocol MVP Backend

Resources:
  ClusterAssignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cluster_assigner.handler
      Runtime: python3.11
      CodeUri: ../lambda/federated/
      MemorySize: 128
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /cluster
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cluster/"
